import React, { createContext, useContext, useState } from 'react';

export type Lang = 'English' | 'Sinhala' | 'Tamil';

const translations = {
  English: {
    home: 'Home', search: 'Search', upload: 'Upload',
    messages: 'Messages', settings: 'Settings',
    myProfile: 'My Profile', editProfile: 'Edit Profile',
    analytics: 'Analytics', followers: 'Followers',
    following: 'Following', posts: 'Posts',
    follow: 'Follow', following_btn: 'Following',
    message: 'Message', logout: 'Logout ',
    noPostsYet: 'No posts yet', uploadArtwork: 'Upload Artwork',
    noSavedPosts: 'No saved posts yet',
    likes: 'likes', like: 'like',
    viewAllComments: 'View all', comment: 'comment',
    addComment: 'Add a comment...', send: 'Send',
    justNowText: 'Just now', mAgo: 'm ago', hAgo: 'h ago', dAgo: 'd ago',
    beFirstComment: 'No comments yet. Be first!',
    loading: 'Loading...', postOptions: 'Post Options',
    deletePost: 'Delete Post', reportPost: 'Report Post',
    cancel: 'Cancel', reported: 'Reported',
    thankYouReport: 'Thank you for your report',
    noPostsYetOwn: 'Share your first artwork!',
    settings_title: 'Settings', account: 'ACCOUNT',
    preferences: 'PREFERENCES', support: 'SUPPORT',
    notifications: 'Notifications', language: 'Language',
    chatTheme: 'Chat Theme', helpCenter: 'Help Center',
    privacyPolicy: 'Privacy Policy', aboutFolkChat: 'About FolkChat',
    changePassword: 'Change Password', darkMode: 'Dark Mode',
    viewAnalytics: 'View Analytics',
    save: 'Save Changes', name: 'Full Name', bio: 'Bio',
    category: 'Artist Category',
    // Delete Account
    deleteAccount: 'Delete Account',
    deleteAccountTitle: 'Delete Account',
    deleteAccountWarningTitle: 'This action cannot be undone',
    deleteAccountWarningText: 'All your posts, comments, followers and account data will be permanently deleted.',
    deleteAccountConfirmLabel: 'Enter your password to confirm',
    deleteAccountBtn: 'Permanently Delete Account',
    deleteAccountStep1Title: 'Are you sure?',
    deleteAccountStep1Body: 'Deleting your account will permanently remove all your artwork, posts, followers, and profile data from FolkChat. This cannot be reversed.',
    deleteAccountStep2Title: 'Confirm Deletion',
    continueBtn: 'Continue',
    // Help Center
    helpHeroTitle: 'How can we help?',
    helpHeroSub: 'Find answers to common questions below',
    faqSectionTitle: 'FREQUENTLY ASKED QUESTIONS',
    faqQ1: 'How do I upload artwork?',
    faqA1: 'Tap the Upload tab at the bottom. Select images or videos from your gallery, add a title and description, then tap Upload.',
    faqQ2: 'Can I upload multiple images?',
    faqA2: 'Yes! You can upload up to 10 images or videos in a single post.',
    faqQ3: 'How do I follow other artists?',
    faqA3: "Visit an artist's profile and tap the Follow button. You can also follow from the home feed.",
    faqQ4: 'How do I edit my profile?',
    faqA4: 'Go to Settings > Edit Profile or tap Edit Profile on your profile page.',
    faqQ5: 'How do I delete a post?',
    faqA5: 'Tap the three dots on any of your posts and select Delete Post.',
    faqQ6: 'How do I save posts?',
    faqA6: 'Tap the bookmark icon on any post to save it. View saved posts in your profile under the bookmark tab.',
    faqQ7: 'How do I delete my account?',
    faqA7: 'Go to Settings > Delete Account. You will need to enter your password to confirm. This will permanently delete all your data.',
    stillNeedHelp: 'Still need help?',
    contactEmail: 'Contact us at support@folkchat.app',
    privacyTitle: 'Privacy Policy', privacyUpdated: 'Last updated: January 2025',
    pp1Title: 'Information We Collect',
    pp1Content: 'We collect information you provide when creating an account, including your name, email address, and profile information. We also collect content you upload such as artwork images and videos.',
    pp2Title: 'How We Use Your Information',
    pp2Content: 'We use your information to provide and improve FolkChat services, personalize your experience, connect you with other folk artists, and send notifications about activity on your account.',
    pp3Title: 'Information Sharing',
    pp3Content: 'Your profile and posts are visible to other FolkChat users. We do not sell your personal information to third parties. We may share information with service providers who help us operate the platform.',
    pp4Title: 'Data Security',
    pp4Content: 'We implement appropriate security measures to protect your information. Your data is stored securely using Firebase services provided by Google.',
    pp5Title: 'Your Rights',
    pp5Content: 'You can access, update, or delete your account information at any time through the app settings. You can also request deletion of your account by contacting us.',
    pp6Title: 'Contact Us',
    pp6Content: 'If you have questions about this Privacy Policy, please contact us at privacy@folkchat.app',
    aboutTagline: 'Connecting Artists, Celebrating Culture',
    aboutVersion: 'Version 1.0.0',
    aboutMissionTitle: 'Our Mission',
    aboutMissionText: "FolkChat is dedicated to preserving and celebrating Sri Lanka's rich folk art traditions. We connect traditional artists with art lovers, creating a vibrant community that keeps our cultural heritage alive.",
    aboutFeaturesTitle: 'Features',
    aboutF1: 'Share artwork and videos', aboutF2: 'Connect with folk artists',
    aboutF3: 'Like, comment and save posts', aboutF4: 'Message artists directly',
    aboutF5: 'Discover folk art categories',
    aboutContactTitle: 'Contact',
    aboutCopyright: 'Made with love for Sri Lankan Folk Artists',
  },

  Sinhala: {
    home: 'මුල් පිටුව', search: 'සොයන්න', upload: 'උඩුගත කරන්න',
    messages: 'පණිවිඩ', settings: 'සැකසුම්',
    myProfile: 'මගේ පැතිකඩ', editProfile: 'පැතිකඩ සංස්කරණය',
    analytics: 'විශ්ලේෂණ', followers: 'අනුගාමිකයන්',
    following: 'අනුගමනය', posts: 'පළ කිරීම්',
    follow: 'අනුගමනය', following_btn: 'අනුගමනය කරයි',
    message: 'පණිවිඩය', logout: 'ඉවත් වන්න',
    noPostsYet: 'තවම පළ කිරීම් නැත', uploadArtwork: 'කලා කෘතිය උඩුගත කරන්න',
    noSavedPosts: 'සුරැකූ පළ කිරීම් නැත',
    likes: 'කැමැත්ත', like: 'කැමැත්ත',
    viewAllComments: 'සියලු', comment: 'අදහස',
    addComment: 'අදහසක් එකතු කරන්න...', send: 'යවන්න',
    justNowText: 'දැන් ම', mAgo: 'මිනි', hAgo: 'පැය', dAgo: 'දින',
    beFirstComment: 'තවම අදහස් නැත. පළමු වන්න!',
    loading: 'පූරණය වෙමින්...', postOptions: 'පළ කිරීමේ විකල්ප',
    deletePost: 'පළ කිරීම මකන්න', reportPost: 'වාර්තා කරන්න',
    cancel: 'අවලංගු', reported: 'වාර්තා කරන ලදි',
    thankYouReport: 'ඔබගේ වාර්තාව ස්තූතියි',
    noPostsYetOwn: 'ඔබේ පළමු කලා කෘතිය බෙදා ගන්න!',
    settings_title: 'සැකසුම්', account: 'ගිණුම',
    preferences: 'මනාපයන්', support: 'සහාය',
    notifications: 'දැනුම් දීම්', language: 'භාෂාව',
    chatTheme: 'චැට් තේමාව', helpCenter: 'උදව් මධ්‍යස්ථානය',
    privacyPolicy: 'රහස්‍යතා ප්‍රතිපත්තිය', aboutFolkChat: 'ෆෝක්චැට් ගැන',
    changePassword: 'මුරපදය වෙනස් කරන්න', darkMode: 'අඳුරු මාදිලිය',
    viewAnalytics: 'විශ්ලේෂණ බලන්න',
    save: 'වෙනස්කම් සුරකින්න', name: 'සම්පූර්ණ නම', bio: 'ජීව කතාව',
    category: 'ශිල්ප වර්ගය',
    deleteAccount: 'ගිණුම මකන්න',
    deleteAccountTitle: 'ගිණුම මකන්න',
    deleteAccountWarningTitle: 'මෙය ආපසු හැරවිය නොහැක',
    deleteAccountWarningText: 'ඔබගේ සියලු posts, comments, followers සහ ගිණුම් දත්ත ස්ථිරවම මකා දමනු ලැබේ.',
    deleteAccountConfirmLabel: 'තහවුරු කිරීමට ඔබේ මුරපදය ඇතුලත් කරන්න',
    deleteAccountBtn: 'ගිණුම ස්ථිරවම මකන්න',
    deleteAccountStep1Title: 'ඔබ ස්ථිරද?',
    deleteAccountStep1Body: 'ඔබේ ගිණුම මකා දැමීමෙන් FolkChat එකේ ඔබේ සියලු කලා කෘති, posts, followers සහ profile දත්ත ස්ථිරවම ඉවත් කෙරෙනවා. මෙය ආපසු හැරවිය නොහැකිය.',
    deleteAccountStep2Title: 'මකා දැමීම තහවුරු කරන්න',
    continueBtn: 'ඉදිරියට',
    helpHeroTitle: 'අපට ඔබට සහාය විය හැකිද?',
    helpHeroSub: 'පොදු ප්‍රශ්නවලට පිළිතුරු සොයන්න',
    faqSectionTitle: 'නිතර අසන ප්‍රශ්න',
    faqQ1: 'කලා කෘතිය කෙසේ upload කරන්නද?',
    faqA1: 'පහළ Upload tab එකේ tap කරන්න. ගැලරි එකේ සිට රූප හෝ වීඩියෝ තෝරන්න, සිරස්තලයක් සහ විස්තරයක් එකතු කරන්න.',
    faqQ2: 'රූප කිහිපයක් upload කළ හැකිද?',
    faqA2: 'ඔව්! ඔබට එක් post එකේ රූප හෝ වීඩියෝ 10ක් දක්වා upload කළ හැක.',
    faqQ3: 'අනෙක් artists එකේ follow කරන්නේ කෙසේද?',
    faqA3: 'Artist එකේ profile එකට ගොස් Follow button tap කරන්න.',
    faqQ4: 'Profile සංස්කරණය කරන්නේ කෙසේද?',
    faqA4: 'Settings > Edit Profile එකට යන්න.',
    faqQ5: 'Post එකක් delete කරන්නේ කෙසේද?',
    faqA5: 'ඔබේ post එකේ ලකුණු තුනේ icon tap කරන්න.',
    faqQ6: 'Posts සුරැකෙන්නේ කෙසේද?',
    faqA6: 'Post එකේ bookmark icon tap කරන්න.',
    faqQ7: 'ගිණුම delete කරන්නේ කෙසේද?',
    faqA7: 'Settings > Delete Account එකට යන්න. ඔබේ මුරපදය ඇතුලත් කර ස්ථිර කරන්න. ඔබේ සියලු දත්ත ස්ථිරවම මකා දමනු ලැබේ.',
    stillNeedHelp: 'තවත් සහාය අවශ්‍යද?',
    contactEmail: 'support@folkchat.app එකේ අපව සම්බන්ධ කරන්න',
    privacyTitle: 'රහස්‍යතා ප්‍රතිපත්තිය', privacyUpdated: 'අවසන් යාවත්කාලීන කිරීම: ජනවාරි 2025',
    pp1Title: 'අපි රැස් කරන තොරතුරු', pp1Content: 'ගිණුමක් සෑදීමේදී ඔබ සපයන නම, ඊමේල් ලිපිනය සහ profile තොරතුරු රැස් කරනවා.',
    pp2Title: 'ඔබේ තොරතුරු භාවිතා කරන ආකාරය', pp2Content: 'FolkChat සේවා සැපයීමට සහ ඔබේ අත්දැකීම පුද්ගලීකරණය කිරීමට ඔබේ තොරතුරු භාවිතා කරනවා.',
    pp3Title: 'තොරතුරු බෙදා ගැනීම', pp3Content: 'ඔබේ profile සහ posts FolkChat users එකේ දිස්වනවා. අපි ඔබේ පුද්ගලික තොරතුරු තෙවන පාර්ශවයන්ට විකුණන්නේ නැහැ.',
    pp4Title: 'දත්ත සුරක්ෂිතතාව', pp4Content: 'ඔබේ දත්ත Google Firebase සේවා හරහා ආරක්ෂිතව ගබඩා කෙරෙනවා.',
    pp5Title: 'ඔබේ අයිතිවාසිකම්', pp5Content: 'Settings හරහා ඕනෑම වේලාවක ගිණුම් තොරතුරු access කර, යාවත්කාලීන කර, හෝ delete කළ හැකියි.',
    pp6Title: 'අප හා සම්බන්ධ වන්න', pp6Content: 'privacy@folkchat.app එකේ අප හා සම්බන්ධ වන්න.',
    aboutTagline: 'කලාකරුවන් සම්බන්ධ කිරීම, සංස්කෘතිය සමරන්න',
    aboutVersion: 'අනුවාදය 1.0.0',
    aboutMissionTitle: 'අපගේ මෙහෙවර',
    aboutMissionText: 'FolkChat ශ්‍රී ලංකාවේ ජන කලා සම්ප්‍රදායන් රැකගැනීමට කැපවී ඇත.',
    aboutFeaturesTitle: 'විශේෂාංග',
    aboutF1: 'කලා කෘති සහ වීඩියෝ බෙදාගන්න', aboutF2: 'ජන කලාකරුවන් සමඟ සම්බන්ධ වන්න',
    aboutF3: 'Like, comment සහ save කරන්න', aboutF4: 'කලාකරුවන්ට සෘජුව message කරන්න',
    aboutF5: 'ජන කලා වර්ග සොයා ගන්න',
    aboutContactTitle: 'සම්බන්ධ කරගන්න',
    aboutCopyright: 'ශ්‍රී ලාංකික ජන කලාකරුවන් වෙනුවෙන් ආදරයෙන් නිර්මාණය කරන ලදි',
  },

  Tamil: {
    home: 'முகப்பு', search: 'தேடு', upload: 'பதிவேற்று',
    messages: 'செய்திகள்', settings: 'அமைப்புகள்',
    myProfile: 'என் சுயவிவரம்', editProfile: 'சுயவிவரம் திருத்து',
    analytics: 'பகுப்பாய்வு', followers: 'பின்தொடர்பவர்கள்',
    following: 'பின்தொடர்கிறது', posts: 'இடுகைகள்',
    follow: 'பின்தொடர்', following_btn: 'பின்தொடர்கிறேன்',
    message: 'செய்தி', logout: 'வெளியேறு',
    noPostsYet: 'இன்னும் இடுகைகள் இல்லை', uploadArtwork: 'கலைப்படைப்பு பதிவேற்று',
    noSavedPosts: 'சேமித்த இடுகைகள் இல்லை',
    likes: 'விருப்பங்கள்', like: 'விருப்பம்',
    viewAllComments: 'அனைத்தும்', comment: 'கருத்து',
    addComment: 'கருத்து சேர்க்கவும்...', send: 'அனுப்பு',
    justNowText: 'இப்போதுதான்', mAgo: 'நிமி', hAgo: 'மணி', dAgo: 'நாள்',
    beFirstComment: 'இன்னும் கருத்துகள் இல்லை. முதலில் இருங்கள்!',
    loading: 'ஏற்றுகிறது...', postOptions: 'இடுகை விருப்பங்கள்',
    deletePost: 'இடுகையை நீக்கு', reportPost: 'புகார் செய்',
    cancel: 'ரத்து செய்', reported: 'புகாரளிக்கப்பட்டது',
    thankYouReport: 'உங்கள் புகாருக்கு நன்றி',
    noPostsYetOwn: 'உங்கள் முதல் படைப்பை பகிரவும்!',
    settings_title: 'அமைப்புகள்', account: 'கணக்கு',
    preferences: 'விருப்பத்தேர்வுகள்', support: 'ஆதரவு',
    notifications: 'அறிவிப்புகள்', language: 'மொழி',
    chatTheme: 'அரட்டை தீம்', helpCenter: 'உதவி மையம்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை', aboutFolkChat: 'FolkChat பற்றி',
    changePassword: 'கடவுச்சொல் மாற்று', darkMode: 'இருண்ட பயன்முறை',
    viewAnalytics: 'பகுப்பாய்வு காண்க',
    save: 'மாற்றங்களை சேமி', name: 'முழு பெயர்', bio: 'சுயவிவரம்',
    category: 'கலை வகை',
    deleteAccount: 'கணக்கை நீக்கு',
    deleteAccountTitle: 'கணக்கை நீக்கு',
    deleteAccountWarningTitle: 'இந்த செயலை மாற்ற முடியாது',
    deleteAccountWarningText: 'உங்கள் அனைத்து இடுகைகள், கருத்துகள், பின்தொடர்பவர்கள் மற்றும் கணக்கு தரவு நிரந்தரமாக நீக்கப்படும்.',
    deleteAccountConfirmLabel: 'உறுதிப்படுத்த உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    deleteAccountBtn: 'கணக்கை நிரந்தரமாக நீக்கு',
    deleteAccountStep1Title: 'நீங்கள் உறுதியாக இருக்கிறீர்களா?',
    deleteAccountStep1Body: 'உங்கள் கணக்கை நீக்குவது FolkChat இலிருந்து உங்கள் அனைத்து படைப்புகள், இடுகைகள், பின்தொடர்பவர்கள் மற்றும் சுயவிவர தரவை நிரந்தரமாக அகற்றும். இதை மாற்ற முடியாது.',
    deleteAccountStep2Title: 'நீக்குதலை உறுதிப்படுத்து',
    continueBtn: 'தொடர்',
    helpHeroTitle: 'நாங்கள் எப்படி உதவலாம்?',
    helpHeroSub: 'பொதுவான கேள்விகளுக்கு பதில்களை கண்டறியுங்கள்',
    faqSectionTitle: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faqQ1: 'கலைப்படைப்பை எவ்வாறு பதிவேற்றுவது?',
    faqA1: 'கீழே உள்ள Upload tab ஐ தட்டவும். கேலரியிலிருந்து படங்கள் தேர்ந்தெடுத்து, தலைப்பு சேர்த்து Upload தட்டவும்.',
    faqQ2: 'பல படங்களை பதிவேற்றலாமா?',
    faqA2: 'ஆம்! ஒரு இடுகையில் 10 படங்கள் வரை பதிவேற்றலாம்.',
    faqQ3: 'மற்ற கலைஞர்களை எவ்வாறு பின்தொடர்வது?',
    faqA3: 'கலைஞரின் சுயவிவரத்தை பார்வையிட்டு Follow தட்டவும்.',
    faqQ4: 'சுயவிவரத்தை எவ்வாறு திருத்துவது?',
    faqA4: 'Settings > Edit Profile க்கு செல்லவும்.',
    faqQ5: 'இடுகையை எவ்வாறு நீக்குவது?',
    faqA5: 'உங்கள் இடுகையில் மூன்று புள்ளிகளை தட்டவும்.',
    faqQ6: 'இடுகைகளை எவ்வாறு சேமிப்பது?',
    faqA6: 'இடுகையில் bookmark icon ஐ தட்டவும்.',
    faqQ7: 'கணக்கை எவ்வாறு நீக்குவது?',
    faqA7: 'Settings > Delete Account க்கு செல்லவும். உங்கள் கடவுச்சொல்லை உள்ளிட்டு உறுதிப்படுத்தவும். உங்கள் அனைத்து தரவும் நிரந்தரமாக நீக்கப்படும்.',
    stillNeedHelp: 'இன்னும் உதவி தேவையா?',
    contactEmail: 'support@folkchat.app இல் தொடர்பு கொள்ளவும்',
    privacyTitle: 'தனியுரிமைக் கொள்கை', privacyUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது: ஜனவரி 2025',
    pp1Title: 'நாங்கள் சேகரிக்கும் தகவல்கள்', pp1Content: 'கணக்கு உருவாக்கும்போது நீங்கள் வழங்கும் பெயர், மின்னஞ்சல் முகவரி மற்றும் சுயவிவர தகவல்களை சேகரிக்கிறோம்.',
    pp2Title: 'உங்கள் தகவல்களை எவ்வாறு பயன்படுத்துகிறோம்', pp2Content: 'FolkChat சேவைகளை வழங்கவும் உங்கள் அனுபவத்தை தனிப்பயனாக்கவும் தகவல்களை பயன்படுத்துகிறோம்.',
    pp3Title: 'தகவல் பகிர்வு', pp3Content: 'உங்கள் சுயவிவரம் மற்றும் இடுகைகள் மற்ற FolkChat பயனர்களுக்கு தெரியும். உங்கள் தகவல்களை மூன்றாம் தரப்பினருக்கு விற்கமாட்டோம்.',
    pp4Title: 'தரவு பாதுகாப்பு', pp4Content: 'உங்கள் தரவு Google Firebase சேவைகள் மூலம் பாதுகாப்பாக சேமிக்கப்படுகிறது.',
    pp5Title: 'உங்கள் உரிமைகள்', pp5Content: 'எப்போது வேண்டுமானாலும் app settings மூலம் கணக்கு தகவல்களை அணுக, புதுப்பிக்க அல்லது நீக்கலாம்.',
    pp6Title: 'தொடர்பு கொள்ளுங்கள்', pp6Content: 'privacy@folkchat.app இல் தொடர்பு கொள்ளவும்.',
    aboutTagline: 'கலைஞர்களை இணைக்கிறோம், கலாச்சாரத்தை கொண்டாடுகிறோம்',
    aboutVersion: 'பதிப்பு 1.0.0',
    aboutMissionTitle: 'எங்கள் நோக்கம்',
    aboutMissionText: 'FolkChat இலங்கையின் நாட்டுப்புற கலை மரபுகளை பாதுகாக்கவும் கொண்டாடவும் அர்ப்பணிக்கப்பட்டுள்ளது.',
    aboutFeaturesTitle: 'அம்சங்கள்',
    aboutF1: 'கலைப்படைப்புகள் மற்றும் வீடியோக்களை பகிரவும்', aboutF2: 'நாட்டுப்புற கலைஞர்களுடன் இணையுங்கள்',
    aboutF3: 'Like, comment மற்றும் சேமிக்கவும்', aboutF4: 'கலைஞர்களுக்கு நேரடியாக செய்தி அனுப்பவும்',
    aboutF5: 'நாட்டுப்புற கலை வகைகளை கண்டறியுங்கள்',
    aboutContactTitle: 'தொடர்பு',
    aboutCopyright: 'இலங்கை நாட்டுப்புற கலைஞர்களுக்காக அன்புடன் உருவாக்கப்பட்டது',
  },
};

interface LangContextType {
  language: Lang;
  setLanguage: (lang: Lang) => void;
  t: typeof translations.English;
}

const defaultContext: LangContextType = {
  language: 'English',
  setLanguage: () => {},
  t: translations.English,
};

const LanguageContext = createContext<LangContextType>(defaultContext);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Lang>('English');
  const t = translations[language];
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);