import React, { createContext, useContext, useState } from 'react';

export type Lang = 'English' | 'Sinhala' | 'Tamil';

const translations = {
  English: {
    home: 'Home', search: 'Search', upload: 'Upload',
    messages: 'Messages', settings: 'Settings',
    myProfile: 'My Profile', editProfile: 'Edit Profile',
    analytics: 'Analytics', followers: 'Followers',
    following: 'Following', posts: 'Posts',
    follow: 'Follow', following_btn: 'Following',
    message: 'Message', logout: 'Logout ',
    noPostsYet: 'No posts yet', uploadArtwork: 'Upload Artwork',
    noSavedPosts: 'No saved posts yet',
    likes: 'likes', like: 'like',
    viewAllComments: 'View all', comment: 'comment',
    addComment: 'Add a comment...', send: 'Send',
    justNowText: 'Just now', mAgo: 'm ago', hAgo: 'h ago', dAgo: 'd ago',
    beFirstComment: 'No comments yet. Be first!',
    loading: 'Loading...', postOptions: 'Post Options',
    deletePost: 'Delete Post', reportPost: 'Report Post',
    cancel: 'Cancel', reported: 'Reported',
    thankYouReport: 'Thank you for your report',
    noPostsYetOwn: 'Share your first artwork!',
    settings_title: 'Settings', account: 'ACCOUNT',
    preferences: 'PREFERENCES', support: 'SUPPORT',
    notifications: 'Notifications', language: 'Language',
    chatTheme: 'Chat Theme', helpCenter: 'Help Center',
    privacyPolicy: 'Privacy Policy', aboutFolkChat: 'About FolkChat',
    changePassword: 'Change Password', darkMode: 'Dark Mode',
    viewAnalytics: 'View Analytics',
    changePwCurrentLabel: 'Current Password',
    changePwNewLabel: 'New Password',
    changePwConfirmLabel: 'Confirm New Password',
    changePwPlaceholder: '••••••••',
    changePwFillAll: 'Please fill all fields',
    changePwNoMatch: 'New passwords do not match',
    changePwTooShort: 'Password must be at least 6 characters',
    changePwSuccess: 'Success',
    changePwSuccessMsg: 'Password changed successfully!',
    changePwUpdateBtn: 'Update Password',
    changePwFailed: 'Failed to change password',
    searchTitle: 'Search',
    searchPlaceholder: 'Search artists, artworks...',
    searchPosts: 'Posts',
    searchArtists: 'Artists',
    searchAllPosts: 'All Posts',
    searchSuggestedTitle: 'Suggested for You',
    searchSuggestedSub: "Artists you don't follow yet",
    searchPostsFound: 'post found',
    searchPostsFoundPlural: 'posts found',
    searchArtistsFound: 'artist found',
    searchArtistsFoundPlural: 'artists found',
    searchNoPostsFound: 'No posts found for',
    searchNoArtistsFound: 'No artists found for',
    searchNoSuggestions: 'No suggestions available',
    searchFollowers: 'followers',
    searchFolkArtist: 'Folk Artist',
    searchViewAllComments: 'View all',
    searchComments: 'comments',
    searchLikes: 'likes',
    searchLike: 'like',
    save: 'Save Changes', name: 'Full Name', bio: 'Bio',
    category: 'Artist Category',
    deleteAccount: 'Delete Account',
    deleteAccountTitle: 'Delete Account',
    deleteAccountWarningTitle: 'This action cannot be undone',
    deleteAccountWarningText: 'All your posts, comments, followers and account data will be permanently deleted.',
    deleteAccountConfirmLabel: 'Enter your password to confirm',
    deleteAccountBtn: 'Permanently Delete Account',
    deleteAccountStep1Title: 'Are you sure?',
    deleteAccountStep1Body: 'Deleting your account will permanently remove all your artwork, posts, followers, and profile data from FolkChat. This cannot be reversed.',
    deleteAccountStep2Title: 'Confirm Deletion',
    continueBtn: 'Continue',
    helpHeroTitle: 'How can we help?',
    helpHeroSub: 'Find answers to common questions below',
    faqSectionTitle: 'FREQUENTLY ASKED QUESTIONS',
    faqQ1: 'How do I upload artwork?',
    faqA1: 'Tap the Upload tab at the bottom. Select images or videos from your gallery, add a title and description, then tap Upload.',
    faqQ2: 'Can I upload multiple images?',
    faqA2: 'Yes! You can upload up to 10 images or videos in a single post.',
    faqQ3: 'How do I follow other artists?',
    faqA3: "Visit an artist's profile and tap the Follow button. You can also follow from the home feed.",
    faqQ4: 'How do I edit my profile?',
    faqA4: 'Go to Settings > Edit Profile or tap Edit Profile on your profile page.',
    faqQ5: 'How do I delete a post?',
    faqA5: 'Tap the three dots on any of your posts and select Delete Post.',
    faqQ6: 'How do I save posts?',
    faqA6: 'Tap the bookmark icon on any post to save it. View saved posts in your profile under the bookmark tab.',
    faqQ7: 'How do I delete my account?',
    faqA7: 'Go to Settings > Delete Account. You will need to enter your password to confirm. This will permanently delete all your data.',
    stillNeedHelp: 'Still need help?',
    contactEmail: 'Contact us at support@folkchat.app',
    privacyTitle: 'Privacy Policy', privacyUpdated: 'Last updated: January 2025',
    pp1Title: 'Information We Collect',
    pp1Content: 'We collect information you provide when creating an account, including your name, email address, and profile information. We also collect content you upload such as artwork images and videos.',
    pp2Title: 'How We Use Your Information',
    pp2Content: 'We use your information to provide and improve FolkChat services, personalize your experience, connect you with other folk artists, and send notifications about activity on your account.',
    pp3Title: 'Information Sharing',
    pp3Content: 'Your profile and posts are visible to other FolkChat users. We do not sell your personal information to third parties. We may share information with service providers who help us operate the platform.',
    pp4Title: 'Data Security',
    pp4Content: 'We implement appropriate security measures to protect your information. Your data is stored securely using Firebase services provided by Google.',
    pp5Title: 'Your Rights',
    pp5Content: 'You can access, update, or delete your account information at any time through the app settings. You can also request deletion of your account by contacting us.',
    pp6Title: 'Contact Us',
    pp6Content: 'If you have questions about this Privacy Policy, please contact us at privacy@folkchat.app',
    aboutTagline: 'Connecting Artists, Celebrating Culture',
    aboutVersion: 'Version 1.0.0',
    aboutMissionTitle: 'Our Mission',
    aboutMissionText: "FolkChat is dedicated to preserving and celebrating Sri Lanka's rich folk art traditions. We connect traditional artists with art lovers, creating a vibrant community that keeps our cultural heritage alive.",
    aboutFeaturesTitle: 'Features',
    aboutF1: 'Share artwork and videos', aboutF2: 'Connect with folk artists',
    aboutF3: 'Like, comment and save posts', aboutF4: 'Message artists directly',
    aboutF5: 'Discover folk art categories',
    aboutContactTitle: 'Contact',
    aboutCopyright: 'Made with love for Sri Lankan Folk Artists',

    uploadArtworkTab: 'Post',
    createEventTab: 'Event',
    uploadArtworkTitle: 'Upload Artwork',
    createEventTitle: 'Create Event',
    artTitle: 'Title',
    artDescription: 'Description',
    artTechniques: 'Techniques',
    artCategory: 'Category',
    titlePlaceholder: 'Give your artwork a title',
    descriptionPlaceholder: 'Describe your artwork...',
    techniquesPlaceholder: 'e.g. Hand woven, Natural dyes...',
    selectCategory: 'Select category...',
    shareArtwork: 'Share Artwork',
    addMoreMedia: 'Add more',
    mediaLimitTitle: 'Limit',
    maxItems: 'Maximum 10 items allowed',
    selectMediaAlert: 'Please select at least one image or video',
    addTitleAlert: 'Please add a title',
    selectCategoryAlert: 'Please select a category',
    uploadingProgress: 'Uploading',
    ofText: 'of',
    savingPost: 'Saving post...',
    postedSuccess: 'Posted!',
    artworkLive: 'Your artwork is live!',
    viewFeed: 'View Feed',
    itemsSelected: 'items selected',
    itemSelected: 'item selected',
    selectCategoryTitle: 'Select Category',
    mediaPickerSub: 'PNG, JPG, MP4 · up to 10 files',
    eventTitleLabel: 'Event Title',
    eventTitlePlaceholder: 'e.g. Batik Exhibition 2025',
    selectEventType: 'Select event type...',
    eventDate: 'Date',
    eventTime: 'Time',
    eventLocation: 'Location',
    eventLocationPlaceholder: 'e.g. Colombo National Museum',
    eventDescriptionPlaceholder: 'Tell people what this event is about...',
    createEventBtn: 'Create Event',
    eventCreated: 'Event Created!',
    eventLive: 'Your event is now visible to everyone.',
    addEventBanner: 'Add event banner (optional)',
    eventTypeLabel: 'Event Type',
    addLocationAlert: 'Please add a location',
    okBtn: 'OK',
    errorTitle: 'Error',
    failedToPost: 'Failed to post',
    failedToCreate: 'Failed to create event',

    folkArtist: 'Folk Artist',
    overview: 'OVERVIEW',
    totalLikes: 'Total Likes',
    totalViews: 'Total Views',
    comments: 'Comments',
    saves: 'Saves',
    avgPerPost: 'avg/post',
    engagementRate: 'Engagement Rate',
    audience: 'Audience',
    activity: 'Activity',
    topPosts: 'Top Posts',
    aiGrowthTips: 'AI Growth Tips',
    industryBenchmarks: 'Industry benchmarks',
    excellent: 'Excellent',
    good: 'Good',
    average: 'Average',
    growing: 'Growing',
    formula: 'Formula',
    interactionBreakdown: 'Interaction breakdown',
    likesLabel: 'Likes',
    commentsLabel: 'Comments',
    savesLabel: 'Saves',
    viewsLabel: 'Views',
    ratio: 'ratio',
    audienceHealthMore: 'Great — more people follow you than you follow!',
    audienceHealthEqual: 'Balanced — equal followers and following.',
    audienceHealthLess: 'Tip — grow your followers to improve your ratio.',
    noActivityHint: 'No activity yet — interactions will appear here',
    untitled: 'Untitled',
    generateAITips: 'Generate AI Tips',
    aiTipsSub: 'Personalized based on your exact stats',
    analyzingStats: 'Analyzing your stats...',
    focus: 'Focus',
    basedOnStats: 'Based on your stats',
    generateNewTips: 'Generate New Tips',
    loadingAnalytics: 'Loading analytics...',
  },

  Sinhala: {
    home: 'මුල් පිටුව', search: 'සොයන්න ', upload: 'උඩුගත කරන්න ',
    messages: 'පණිවිඩ ', settings: 'සැකසුම් ',
    myProfile: 'මගේ පැතිකඩ', editProfile: 'පැතිකඩ සංස්කරණය ',
    analytics: 'විශ්ලේෂණ', followers: 'අනුගාමිකයන්',
    following: 'අනුගමනය', posts: 'පළ කිරීම්',
    follow: 'අනුගමනය ', following_btn: 'අනුගමනය කරයි ',
    message: 'පණිවිඩය', logout: 'ඉවත් වන්න',
    noPostsYet: 'තවම පළ කිරීම් නැත', uploadArtwork: 'කලා කෘතිය උඩුගත කරන්න ',
    noSavedPosts: 'සුරැකූ පළ කිරීම් නැත',
    likes: 'කැමැත්ත', like: 'කැමැත්ත',
    viewAllComments: 'සියලු', comment: 'අදහස',
    addComment: 'අදහසක් එකතු කරන්න...', send: 'යවන්න',
    justNowText: 'දැන් ම', mAgo: 'මිනි', hAgo: 'පැය', dAgo: 'දින',
    beFirstComment: 'තවම අදහස් නැත. පළමු වන්න!',
    loading: 'පූරණය වෙමින්...', postOptions: 'පළ කිරීමේ විකල්ප',
    deletePost: 'පළ කිරීම මකන්න', reportPost: 'වාර්තා කරන්න',
    cancel: 'අවලංගු', reported: 'වාර්තා කරන ලදි',
    thankYouReport: 'ඔබගේ වාර්තාව ස්තූතියි',
    noPostsYetOwn: 'ඔබේ පළමු කලා කෘතිය බෙදා ගන්න!',
    settings_title: 'සැකසුම්', account: 'ගිණුම',
    preferences: 'මනාපයන්', support: 'සහාය',
    notifications: 'දැනුම් දීම්', language: 'භාෂාව',
    chatTheme: 'චැට් තේමාව', helpCenter: 'උදව් මධ්‍යස්ථානය',
    privacyPolicy: 'රහස්‍යතා ප්‍රතිපත්තිය', aboutFolkChat: 'ෆෝක්චැට් ගැන',
    changePassword: 'මුරපදය වෙනස් කරන්න', darkMode: 'අඳුරු මාදිලිය',
    viewAnalytics: 'විශ්ලේෂණ බලන්න',
    changePwCurrentLabel: 'වත්මන් මුරපදය',
    changePwNewLabel: 'නව මුරපදය',
    changePwConfirmLabel: 'නව මුරපදය තහවුරු කරන්න',
    changePwPlaceholder: '••••••••',
    changePwFillAll: 'කරුණාකර සියලු ක්ෂේත්‍ර පුරවන්න',
    changePwNoMatch: 'නව මුරපද නොගැලපේ',
    changePwTooShort: 'මුරපදය අවම වශයෙන් අකුරු 6ක් විය යුතුය',
    changePwSuccess: 'සාර්ථකයි',
    changePwSuccessMsg: 'මුරපදය සාර්ථකව වෙනස් කරන ලදි!',
    changePwUpdateBtn: 'මුරපදය යාවත්කාලීන කරන්න',
    changePwFailed: 'මුරපදය වෙනස් කිරීම අසාර්ථකයි',
    searchTitle: 'සොයන්න',
    searchPlaceholder: 'කලාකරුවන්, කලා කෘති සොයන්න...',
    searchPosts: 'පළ කිරීම්',
    searchArtists: 'කලාකරුවන්',
    searchAllPosts: 'සියලු පළ කිරීම්',
    searchSuggestedTitle: 'ඔබට යෝජිත',
    searchSuggestedSub: 'ඔබ තවම follow නොකරන කලාකරුවන්',
    searchPostsFound: 'පළ කිරීමක් හමු විය',
    searchPostsFoundPlural: 'පළ කිරීම් හමු විය',
    searchArtistsFound: 'කලාකරුවෙකු හමු විය',
    searchArtistsFoundPlural: 'කලාකරුවන් හමු විය',
    searchNoPostsFound: 'සඳහා පළ කිරීම් හමු නොවිය',
    searchNoArtistsFound: 'සඳහා කලාකරුවන් හමු නොවිය',
    searchNoSuggestions: 'යෝජනා නොමැත',
    searchFollowers: 'අනුගාමිකයන්',
    searchFolkArtist: 'ජන කලාකරු',
    searchViewAllComments: 'සියලු',
    searchComments: 'අදහස්',
    searchLikes: 'කැමැත්ත',
    searchLike: 'කැමැත්ත',
    save: 'වෙනස්කම් සුරකින්න', name: 'සම්පූර්ණ නම', bio: 'ජීව කතාව',
    category: 'ශිල්ප වර්ගය',
    deleteAccount: 'ගිණුම මකන්න',
    deleteAccountTitle: 'ගිණුම මකන්න',
    deleteAccountWarningTitle: 'මෙය ආපසු හැරවිය නොහැක',
    deleteAccountWarningText: 'ඔබගේ සියලු posts, comments, followers සහ ගිණුම් දත්ත ස්ථිරවම මකා දමනු ලැබේ.',
    deleteAccountConfirmLabel: 'තහවුරු කිරීමට ඔබේ මුරපදය ඇතුලත් කරන්න',
    deleteAccountBtn: 'ගිණුම ස්ථිරවම මකන්න',
    deleteAccountStep1Title: 'ඔබ ස්ථිරද?',
    deleteAccountStep1Body: 'ඔබේ ගිණුම මකා දැමීමෙන් FolkChat එකේ ඔබේ සියලු කලා කෘති, posts, followers සහ profile දත්ත ස්ථිරවම ඉවත් කෙරෙනවා. මෙය ආපසු හැරවිය නොහැකිය.',
    deleteAccountStep2Title: 'මකා දැමීම තහවුරු කරන්න',
    continueBtn: 'ඉදිරියට',
    helpHeroTitle: 'අපට ඔබට සහාය විය හැකිද?',
    helpHeroSub: 'පොදු ප්‍රශ්නවලට පිළිතුරු සොයන්න',
    faqSectionTitle: 'නිතර අසන ප්‍රශ්න',
    faqQ1: 'කලා කෘතිය කෙසේ upload කරන්නද?',
    faqA1: 'පහළ Upload tab එකේ tap කරන්න. ගැලරි එකේ සිට රූප හෝ වීඩියෝ තෝරන්න.',
    faqQ2: 'රූප කිහිපයක් upload කළ හැකිද?',
    faqA2: 'ඔව්! එක් post එකේ රූප 10ක් දක්වා upload කළ හැක.',
    faqQ3: 'අනෙක් artists follow කරන්නේ කෙසේද?',
    faqA3: 'Artist එකේ profile එකට ගොස් Follow tap කරන්න.',
    faqQ4: 'Profile සංස්කරණය කරන්නේ කෙසේද?',
    faqA4: 'Settings > Edit Profile එකට යන්න.',
    faqQ5: 'Post එකක් delete කරන්නේ කෙසේද?',
    faqA5: 'Post එකේ ලකුණු තුනේ icon tap කරන්න.',
    faqQ6: 'Posts සුරැකෙන්නේ කෙසේද?',
    faqA6: 'Post එකේ bookmark icon tap කරන්න.',
    faqQ7: 'ගිණුම delete කරන්නේ කෙසේද?',
    faqA7: 'Settings > Delete Account එකට යන්න.',
    stillNeedHelp: 'තවත් සහාය අවශ්‍යද?',
    contactEmail: 'support@folkchat.app එකේ අපව සම්බන්ධ කරන්න',
    privacyTitle: 'රහස්‍යතා ප්‍රතිපත්තිය', privacyUpdated: 'අවසන් යාවත්කාලීන කිරීම: ජනවාරි 2025',
    pp1Title: 'අපි රැස් කරන තොරතුරු', pp1Content: 'ගිණුමක් සෑදීමේදී ඔබ සපයන තොරතුරු රැස් කරනවා.',
    pp2Title: 'ඔබේ තොරතුරු භාවිතා කරන ආකාරය', pp2Content: 'FolkChat සේවා සැපයීමට ඔබේ තොරතුරු භාවිතා කරනවා.',
    pp3Title: 'තොරතුරු බෙදා ගැනීම', pp3Content: 'ඔබේ posts FolkChat users එකේ දිස්වනවා.',
    pp4Title: 'දත්ත සුරක්ෂිතතාව', pp4Content: 'Google Firebase හරහා ආරක්ෂිතව ගබඩා කෙරෙනවා.',
    pp5Title: 'ඔබේ අයිතිවාසිකම්', pp5Content: 'Settings හරහා ඕනෑම වේලාවක ගිණුම් access කළ හැකියි.',
    pp6Title: 'අප හා සම්බන්ධ වන්න', pp6Content: 'privacy@folkchat.app එකේ අප හා සම්බන්ධ වන්න.',
    aboutTagline: 'කලාකරුවන් සම්බන්ධ කිරීම, සංස්කෘතිය සමරන්න',
    aboutVersion: 'අනුවාදය 1.0.0',
    aboutMissionTitle: 'අපගේ මෙහෙවර',
    aboutMissionText: 'FolkChat ශ්‍රී ලංකාවේ ජන කලා සම්ප්‍රදායන් රැකගැනීමට කැපවී ඇත.',
    aboutFeaturesTitle: 'විශේෂාංග',
    aboutF1: 'කලා කෘති සහ වීඩියෝ බෙදාගන්න', aboutF2: 'ජන කලාකරුවන් සමඟ සම්බන්ධ වන්න',
    aboutF3: 'Like, comment සහ save කරන්න', aboutF4: 'කලාකරුවන්ට message කරන්න',
    aboutF5: 'ජන කලා වර්ග සොයා ගන්න',
    aboutContactTitle: 'සම්බන්ධ කරගන්න',
    aboutCopyright: 'ශ්‍රී ලාංකික ජන කලාකරුවන් වෙනුවෙන් ආදරයෙන් නිර්මාණය කරන ලදි',

    uploadArtworkTab: 'පළ කිරීම',
    createEventTab: 'උත්සවය',
    uploadArtworkTitle: 'කලා කෘතිය උඩුගත කරන්න',
    createEventTitle: 'උත්සවයක් සාදන්න',
    artTitle: 'මාතෘකාව',
    artDescription: 'විස්තරය',
    artTechniques: 'ශිල්ප ක්‍රම',
    artCategory: 'වර්ගය',
    titlePlaceholder: 'ඔබේ කලා කෘතියට මාතෘකාවක් දෙන්න',
    descriptionPlaceholder: 'ඔබේ කලා කෘතිය ගැන විස්තර කරන්න...',
    techniquesPlaceholder: 'උදා: අත් වියන ලද, ස්වාභාවික රෙදි...',
    selectCategory: 'වර්ගය තෝරන්න...',
    shareArtwork: 'කලා කෘතිය බෙදාගන්න',
    addMoreMedia: 'තව එකතු කරන්න',
    mediaLimitTitle: 'සීමාව',
    maxItems: 'උපරිම ගොනු 10ක් පමණයි',
    selectMediaAlert: 'කරුණාකර අවම වශයෙන් රූපයක් තෝරන්න',
    addTitleAlert: 'කරුණාකර මාතෘකාවක් එකතු කරන්න',
    selectCategoryAlert: 'කරුණාකර වර්ගයක් තෝරන්න',
    uploadingProgress: 'උඩුගත කරමින්',
    ofText: 'න්',
    savingPost: 'සුරකිමින්...',
    postedSuccess: 'පළ කරන ලදි!',
    artworkLive: 'ඔබේ කලා කෘතිය දැන් සජීවීව ඇත!',
    viewFeed: 'ෆීඩ් බලන්න',
    itemsSelected: 'ගොනු තෝරා ගන්නා ලදි',
    itemSelected: 'ගොනුව තෝරා ගන්නා ලදි',
    selectCategoryTitle: 'වර්ගය තෝරන්න',
    mediaPickerSub: 'PNG, JPG, MP4 · ගොනු 10ක් දක්වා',
    eventTitleLabel: 'උත්සව මාතෘකාව',
    eventTitlePlaceholder: 'උදා: Batik Exhibition 2025',
    selectEventType: 'උත්සව වර්ගය තෝරන්න...',
    eventDate: 'දිනය',
    eventTime: 'වේලාව',
    eventLocation: 'ස්ථානය',
    eventLocationPlaceholder: 'උදා: කොළඹ ජාතික කෞතුකාගාරය',
    eventDescriptionPlaceholder: 'මෙම උත්සවය ගැන මිනිසුන්ට කියන්න...',
    createEventBtn: 'උත්සවය සාදන්න',
    eventCreated: 'උත්සවය සාදන ලදි!',
    eventLive: 'ඔබේ උත්සවය දැන් සෑම කෙනෙකුටම දිස්වේ.',
    addEventBanner: 'උත්සව බැනරයක් එකතු කරන්න (විකල්ප)',
    eventTypeLabel: 'උත්සව වර්ගය',
    addLocationAlert: 'කරුණාකර ස්ථානයක් එකතු කරන්න',
    okBtn: 'හරි',
    errorTitle: 'දෝෂයකි',
    failedToPost: 'පළ කිරීම අසාර්ථකයි',
    failedToCreate: 'උත්සවය සෑදීම අසාර්ථකයි',

    folkArtist: 'ජන කලාකරු',
    overview: 'දළ විශ්ලේෂණය',
    totalLikes: 'මුළු කැමැත්ත',
    totalViews: 'මුළු දර්ශන',
    comments: 'අදහස්',
    saves: 'සුරැකූ',
    avgPerPost: 'සාමාන්‍යය/පළ',
    engagementRate: 'සම්බන්ධතා අනුපාතය',
    audience: 'ප්‍රේක්ෂකයන්',
    activity: 'ක්‍රියාකාරකම්',
    topPosts: 'ප්‍රමුඛ පළ කිරීම්',
    aiGrowthTips: 'AI වර්ධන උපදෙස්',
    industryBenchmarks: 'කර්මාන්ත සම්මත',
    excellent: 'විශිෂ්ටයි',
    good: 'හොඳයි',
    average: 'සාමාන්‍යයි',
    growing: 'වර්ධනය වෙමින්',
    formula: 'සූත්‍රය',
    interactionBreakdown: 'අන්තර්ක්‍රියා බෙදීම',
    likesLabel: 'කැමති',
    commentsLabel: 'අදහස්',
    savesLabel: 'සුරැකූ',
    viewsLabel: 'දර්ශන',
    ratio: 'අනුපාතය',
    audienceHealthMore: 'හොඳයි — ඔබට අනුගමනය කරන සංඛ්‍යාව වැඩියි!',
    audienceHealthEqual: 'සමතුලිතයි — සමාන අනුගාමිකයන් සහ අනුගමනය.',
    audienceHealthLess: 'උපදෙස් — ඔබේ අනුගාමිකයන් වැඩි කරන්න.',
    noActivityHint: 'තවම ක්‍රියාකාරකම් නැත — මෙහි දිස්වනු ඇත',
    untitled: 'මාතෘකාවක් නැත',
    generateAITips: 'AI උපදෙස් ලබා ගන්න',
    aiTipsSub: 'ඔබේ දත්ත අනුව පුද්ගලීකරණය කරන ලදි',
    analyzingStats: 'ඔබේ දත්ත විශ්ලේෂණය කරමින්...',
    focus: 'අවධානය',
    basedOnStats: 'ඔබේ දත්ත මත පදනම්ව',
    generateNewTips: 'නව උපදෙස් ලබා ගන්න',
    loadingAnalytics: 'විශ්ලේෂණ පූරණය කරමින්...',
  },

  Tamil: {
    home: 'முகப்பு', search: 'தேடு', upload: 'பதிவேற்று',
    messages: 'செய்திகள்', settings: 'அமைப்புகள்',
    myProfile: 'என் சுயவிவரம்', editProfile: 'சுயவிவரம் திருத்து',
    analytics: 'பகுப்பாய்வு', followers: 'பின்தொடர்பவர்கள்',
    following: 'பின்தொடர்கிறது', posts: 'இடுகைகள்',
    follow: 'பின்தொடர்', following_btn: 'பின்தொடர்கிறேன்',
    message: 'செய்தி', logout: 'வெளியேறு',
    noPostsYet: 'இன்னும் இடுகைகள் இல்லை', uploadArtwork: 'கலைப்படைப்பு பதிவேற்று',
    noSavedPosts: 'சேமித்த இடுகைகள் இல்லை',
    likes: 'விருப்பங்கள்', like: 'விருப்பம்',
    viewAllComments: 'அனைத்தும்', comment: 'கருத்து',
    addComment: 'கருத்து சேர்க்கவும்...', send: 'அனுப்பு',
    justNowText: 'இப்போதுதான்', mAgo: 'நிமி', hAgo: 'மணி', dAgo: 'நாள்',
    beFirstComment: 'இன்னும் கருத்துகள் இல்லை. முதலில் இருங்கள்!',
    loading: 'ஏற்றுகிறது...', postOptions: 'இடுகை விருப்பங்கள்',
    deletePost: 'இடுகையை நீக்கு', reportPost: 'புகார் செய்',
    cancel: 'ரத்து செய்', reported: 'புகாரளிக்கப்பட்டது',
    thankYouReport: 'உங்கள் புகாருக்கு நன்றி',
    noPostsYetOwn: 'உங்கள் முதல் படைப்பை பகிரவும்!',
    settings_title: 'அமைப்புகள்', account: 'கணக்கு',
    preferences: 'விருப்பத்தேர்வுகள்', support: 'ஆதரவு',
    notifications: 'அறிவிப்புகள்', language: 'மொழி',
    chatTheme: 'அரட்டை தீம்', helpCenter: 'உதவி மையம்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை', aboutFolkChat: 'FolkChat பற்றி',
    changePassword: 'கடவுச்சொல் மாற்று', darkMode: 'இருண்ட பயன்முறை',
    viewAnalytics: 'பகுப்பாய்வு காண்க',
    changePwCurrentLabel: 'தற்போதைய கடவுச்சொல்',
    changePwNewLabel: 'புதிய கடவுச்சொல்',
    changePwConfirmLabel: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்து',
    changePwPlaceholder: '••••••••',
    changePwFillAll: 'அனைத்து புலங்களையும் நிரப்பவும்',
    changePwNoMatch: 'புதிய கடவுச்சொற்கள் பொருந்தவில்லை',
    changePwTooShort: 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்கள் இருக்க வேண்டும்',
    changePwSuccess: 'வெற்றி',
    changePwSuccessMsg: 'கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது!',
    changePwUpdateBtn: 'கடவுச்சொல்லை புதுப்பி',
    changePwFailed: 'கடவுச்சொல்லை மாற்ற முடியவில்லை',
    searchTitle: 'தேடு',
    searchPlaceholder: 'கலைஞர்கள், கலைப்படைப்புகள் தேடவும்...',
    searchPosts: 'இடுகைகள்',
    searchArtists: 'கலைஞர்கள்',
    searchAllPosts: 'அனைத்து இடுகைகள்',
    searchSuggestedTitle: 'உங்களுக்கான பரிந்துரைகள்',
    searchSuggestedSub: 'நீங்கள் இன்னும் பின்தொடராத கலைஞர்கள்',
    searchPostsFound: 'இடுகை கிடைத்தது',
    searchPostsFoundPlural: 'இடுகைகள் கிடைத்தன',
    searchArtistsFound: 'கலைஞர் கிடைத்தார்',
    searchArtistsFoundPlural: 'கலைஞர்கள் கிடைத்தனர்',
    searchNoPostsFound: 'க்கான இடுகைகள் இல்லை',
    searchNoArtistsFound: 'க்கான கலைஞர்கள் இல்லை',
    searchNoSuggestions: 'பரிந்துரைகள் இல்லை',
    searchFollowers: 'பின்தொடர்பவர்கள்',
    searchFolkArtist: 'நாட்டுப்புற கலைஞர்',
    searchViewAllComments: 'அனைத்தும்',
    searchComments: 'கருத்துகள்',
    searchLikes: 'விருப்பங்கள்',
    searchLike: 'விருப்பம்',
    save: 'மாற்றங்களை சேமி', name: 'முழு பெயர்', bio: 'சுயவிவரம்',
    category: 'கலை வகை',
    deleteAccount: 'கணக்கை நீக்கு',
    deleteAccountTitle: 'கணக்கை நீக்கு',
    deleteAccountWarningTitle: 'இந்த செயலை மாற்ற முடியாது',
    deleteAccountWarningText: 'உங்கள் அனைத்து இடுகைகள், கருத்துகள் நிரந்தரமாக நீக்கப்படும்.',
    deleteAccountConfirmLabel: 'உறுதிப்படுத்த உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    deleteAccountBtn: 'கணக்கை நிரந்தரமாக நீக்கு',
    deleteAccountStep1Title: 'நீங்கள் உறுதியாக இருக்கிறீர்களா?',
    deleteAccountStep1Body: 'உங்கள் கணக்கை நீக்குவது அனைத்து தரவையும் நிரந்தரமாக அகற்றும்.',
    deleteAccountStep2Title: 'நீக்குதலை உறுதிப்படுத்து',
    continueBtn: 'தொடர்',
    helpHeroTitle: 'நாங்கள் எப்படி உதவலாம்?',
    helpHeroSub: 'பொதுவான கேள்விகளுக்கு பதில்களை கண்டறியுங்கள்',
    faqSectionTitle: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faqQ1: 'கலைப்படைப்பை எவ்வாறு பதிவேற்றுவது?',
    faqA1: 'கீழே உள்ள Upload tab ஐ தட்டவும்.',
    faqQ2: 'பல படங்களை பதிவேற்றலாமா?',
    faqA2: 'ஆம்! 10 படங்கள் வரை.',
    faqQ3: 'மற்ற கலைஞர்களை எவ்வாறு பின்தொடர்வது?',
    faqA3: 'Follow தட்டவும்.',
    faqQ4: 'சுயவிவரத்தை எவ்வாறு திருத்துவது?',
    faqA4: 'Settings > Edit Profile.',
    faqQ5: 'இடுகையை எவ்வாறு நீக்குவது?',
    faqA5: 'மூன்று புள்ளிகளை தட்டவும்.',
    faqQ6: 'இடுகைகளை எவ்வாறு சேமிப்பது?',
    faqA6: 'bookmark icon ஐ தட்டவும்.',
    faqQ7: 'கணக்கை எவ்வாறு நீக்குவது?',
    faqA7: 'Settings > Delete Account.',
    stillNeedHelp: 'இன்னும் உதவி தேவையா?',
    contactEmail: 'support@folkchat.app',
    privacyTitle: 'தனியுரிமைக் கொள்கை', privacyUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது: ஜனவரி 2025',
    pp1Title: 'நாங்கள் சேகரிக்கும் தகவல்கள்', pp1Content: 'கணக்கு உருவாக்கும்போது தகவல்களை சேகரிக்கிறோம்.',
    pp2Title: 'உங்கள் தகவல்களை எவ்வாறு பயன்படுத்துகிறோம்', pp2Content: 'சேவைகளை வழங்க பயன்படுத்துகிறோம்.',
    pp3Title: 'தகவல் பகிர்வு', pp3Content: 'சுயவிவரம் பயனர்களுக்கு தெரியும்.',
    pp4Title: 'தரவு பாதுகாப்பு', pp4Content: 'Firebase மூலம் பாதுகாக்கப்படுகிறது.',
    pp5Title: 'உங்கள் உரிமைகள்', pp5Content: 'எப்போது வேண்டுமானாலும் அணுகலாம்.',
    pp6Title: 'தொடர்பு கொள்ளுங்கள்', pp6Content: 'privacy@folkchat.app.',
    aboutTagline: 'கலைஞர்களை இணைக்கிறோம், கலாச்சாரத்தை கொண்டாடுகிறோம்',
    aboutVersion: 'பதிப்பு 1.0.0',
    aboutMissionTitle: 'எங்கள் நோக்கம்',
    aboutMissionText: 'FolkChat இலங்கையின் நாட்டுப்புற கலையை பாதுகாக்கிறது.',
    aboutFeaturesTitle: 'அம்சங்கள்',
    aboutF1: 'கலைப்படைப்புகளை பகிரவும்', aboutF2: 'கலைஞர்களுடன் இணையுங்கள்',
    aboutF3: 'Like, comment செய்யுங்கள்', aboutF4: 'நேரடியாக செய்தி அனுப்பவும்',
    aboutF5: 'கலை வகைகளை கண்டறியுங்கள்',
    aboutContactTitle: 'தொடர்பு',
    aboutCopyright: 'இலங்கை கலைஞர்களுக்காக உருவாக்கப்பட்டது',

    uploadArtworkTab: 'இடுகை',
    createEventTab: 'நிகழ்வு',
    uploadArtworkTitle: 'கலைப்படைப்பு பதிவேற்று',
    createEventTitle: 'நிகழ்வை உருவாக்கு',
    artTitle: 'தலைப்பு',
    artDescription: 'விளக்கம்',
    artTechniques: 'நுட்பங்கள்',
    artCategory: 'வகை',
    titlePlaceholder: 'உங்கள் படைப்புக்கு தலைப்பு கொடுங்கள்',
    descriptionPlaceholder: 'உங்கள் கலைப்படைப்பை விவரிக்கவும்...',
    techniquesPlaceholder: 'எ.கா. கை நெய்த, இயற்கை சாயங்கள்...',
    selectCategory: 'வகை தேர்ந்தெடுக்கவும்...',
    shareArtwork: 'கலைப்படைப்பை பகிரவும்',
    addMoreMedia: 'மேலும் சேர்க்கவும்',
    mediaLimitTitle: 'வரம்பு',
    maxItems: 'அதிகபட்சம் 10 கோப்புகள்',
    selectMediaAlert: 'குறைந்தது ஒரு படம் தேர்ந்தெடுக்கவும்',
    addTitleAlert: 'தலைப்பு சேர்க்கவும்',
    selectCategoryAlert: 'வகை தேர்ந்தெடுக்கவும்',
    uploadingProgress: 'பதிவேற்றுகிறது',
    ofText: 'இல்',
    savingPost: 'சேமிக்கிறது...',
    postedSuccess: 'பதிவிடப்பட்டது!',
    artworkLive: 'உங்கள் படைப்பு நேரலையில் உள்ளது!',
    viewFeed: 'ஊட்டம் காண்க',
    itemsSelected: 'கோப்புகள் தேர்ந்தெடுக்கப்பட்டன',
    itemSelected: 'கோப்பு தேர்ந்தெடுக்கப்பட்டது',
    selectCategoryTitle: 'வகை தேர்ந்தெடுக்கவும்',
    mediaPickerSub: 'PNG, JPG, MP4 · 10 கோப்புகள் வரை',
    eventTitleLabel: 'நிகழ்வு தலைப்பு',
    eventTitlePlaceholder: 'எ.கா. Batik Exhibition 2025',
    selectEventType: 'நிகழ்வு வகை தேர்ந்தெடுக்கவும்...',
    eventDate: 'தேதி',
    eventTime: 'நேரம்',
    eventLocation: 'இடம்',
    eventLocationPlaceholder: 'எ.கா. கொழும்பு தேசிய அருங்காட்சியகம்',
    eventDescriptionPlaceholder: 'நிகழ்வைப் பற்றி கூறுங்கள்...',
    createEventBtn: 'நிகழ்வை உருவாக்கு',
    eventCreated: 'நிகழ்வு உருவாக்கப்பட்டது!',
    eventLive: 'உங்கள் நிகழ்வு அனைவருக்கும் தெரியும்.',
    addEventBanner: 'நிகழ்வு பேனர் சேர்க்கவும் (விரும்பினால்)',
    eventTypeLabel: 'நிகழ்வு வகை',
    addLocationAlert: 'இடத்தை சேர்க்கவும்',
    okBtn: 'சரி',
    errorTitle: 'பிழை',
    failedToPost: 'பதிவிட முடியவில்லை',
    failedToCreate: 'நிகழ்வை உருவாக்க முடியவில்லை',

    folkArtist: 'நாட்டுப்புற கலைஞர்',
    overview: 'மேலோட்டம்',
    totalLikes: 'மொத்த விருப்பங்கள்',
    totalViews: 'மொத்த காட்சிகள்',
    comments: 'கருத்துகள்',
    saves: 'சேமிப்புகள்',
    avgPerPost: 'சராசரி/இடுகை',
    engagementRate: 'ஈடுபாட்டு விகிதம்',
    audience: 'பார்வையாளர்கள்',
    activity: 'செயல்பாடு',
    topPosts: 'சிறந்த இடுகைகள்',
    aiGrowthTips: 'AI வளர்ச்சி குறிப்புகள்',
    industryBenchmarks: 'தொழில் தரநிலைகள்',
    excellent: 'சிறந்த',
    good: 'நன்று',
    average: 'சராசரி',
    growing: 'வளர்கிறது',
    formula: 'சூத்திரம்',
    interactionBreakdown: 'தொடர்பு பகுப்பாய்வு',
    likesLabel: 'விருப்பங்கள்',
    commentsLabel: 'கருத்துகள்',
    savesLabel: 'சேமிப்புகள்',
    viewsLabel: 'காட்சிகள்',
    ratio: 'விகிதம்',
    audienceHealthMore: 'நன்று — உங்களை அதிகம் பின்தொடர்கிறார்கள்!',
    audienceHealthEqual: 'சமநிலை — சம பின்தொடர்பவர்கள்.',
    audienceHealthLess: 'குறிப்பு — பின்தொடர்பவர்களை அதிகரிக்கவும்.',
    noActivityHint: 'செயல்பாடு இல்லை — இங்கே தோன்றும்',
    untitled: 'தலைப்பு இல்லை',
    generateAITips: 'AI குறிப்புகள் உருவாக்கு',
    aiTipsSub: 'உங்கள் தரவின் அடிப்படையில் தனிப்பயனாக்கப்பட்டது',
    analyzingStats: 'தரவை பகுப்பாய்வு செய்கிறது...',
    focus: 'கவனம்',
    basedOnStats: 'உங்கள் தரவின் அடிப்படையில்',
    generateNewTips: 'புதிய குறிப்புகள் உருவாக்கு',
    loadingAnalytics: 'பகுப்பாய்வு ஏற்றுகிறது...',
  },
};

interface LangContextType {
  language: Lang;
  setLanguage: (lang: Lang) => void;
  t: typeof translations.English;
}

const defaultContext: LangContextType = {
  language: 'English',
  setLanguage: () => {},
  t: translations.English,
};

const LanguageContext = createContext<LangContextType>(defaultContext);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Lang>('English');
  const t = translations[language];
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);